# Generated by Django 2.1 on 2019-02-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190105_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
