# Generated by Django 2.1 on 2019-03-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_formauthor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormAuthor',
        ),
    ]
